
name = "nkumbamarketplace"
compatibility_date = "2026-08-06"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "nkumba-db"
database_id = "c660b683-8bb0-4247-bb92-490ebf1261f3"
